// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cknwowuaqymprfaylwti.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNrbndvd3VhcXltcHJmYXlsd3RpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5OTYyNzUsImV4cCI6MjA2NTU3MjI3NX0.dPKnFeUMeufXNyO531OPXhT-s0DeJVyJIV2fhbRcL3Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);